export enum ZoneStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  REASSIGNMENT_FAILED = 'REASSIGNMENT_FAILED',
  REASSIGNMENT_PENDING = 'REASSIGNMENT_PENDING',
  REASSIGNMENT_SUCCESS = 'REASSIGNMENT_SUCCESS',
}
